### PR TITLE
On error page delete stored partition and queue

### LINKED ISSUE #385: Clear preselected items if loading fails
Trying to load queues and partitions with stored ID's might result in failure if the data is missing for any reason, and that will redirect to the /error page.
If that happens, just remove the stored data, and when user returns to the applications page they might be able to select a different queue and partition

### PR DESCRIPTION
**Pull request by dcoric**
### What is this PR for?
Fixes an issue with stored queue and partition. When the page is reloaded and that info is gone page will crash. On the error page, that info will be removed from storage

### What type of PR is it?
* [x] - Bug Fix
* [ ] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### CODE REVIEW

File: src/app/components/error-view/error-view.component.ts [hunk 1]
```diff
@@ -34,6 +35,7 @@ export class ErrorViewComponent implements OnInit {
   ngOnInit() {
     this.apiError = window.history.state;
     this.lastActiveUrl = this.activatedRoute.snapshot.queryParams['last'];
+    CommonUtil.setStoredQueueAndPartition('');
```
Comment (dave-gantenbein) [inline src/app/components/error-view/error-view.component.ts:38]: Should this have a test?

Comment (dcoric) [reply src/app/components/error-view/error-view.component.ts:38]: Yes. The test is added.

**Review by dave-gantenbein — APPROVED** [review]
